import { fontSans } from '@/config/fonts';
import { HeroUIProvider } from '@heroui/react';
import clsx from 'clsx';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={clsx(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
